public class Data {
    public static String[] firstNames = (
            "Liam\n" +
            "Noah\n" +
            "Olivia\n" +
            "Emma\n" +
            "Ava\n" +
            "Oliver\n" +
            "Sophia\n" +
            "William\n" +
            "Elijah\n" +
            "Isabella\n" +
            "James\n" +
            "Charlotte\n" +
            "Benjamin\n" +
            "Amelia\n" +
            "Lucas\n" +
            "Mia\n" +
            "Logan\n" +
            "Ethan\n" +
            "Alexander\n" +
            "Henry\n" +
            "Jacob\n" +
            "Harper\n" +
            "Michael\n" +
            "Daniel\n" +
            "Evelyn\n" +
            "Jackson\n" +
            "Sebastian\n" +
            "Aiden\n" +
            "Jack\n" +
            "Owen\n" +
            "Samuel\n" +
            "Carter\n" +
            "Avery\n" +
            "Matthew\n" +
            "Abigail\n" +
            "Levi\n" +
            "Mateo\n" +
            "David\n" +
            "Wyatt\n" +
            "John\n" +
            "Julian\n" +
            "Luke\n" +
            "Grayson\n" +
            "Emily\n" +
            "Isaac\n" +
            "Jayden\n" +
            "Ella\n" +
            "Elizabeth\n" +
            "Theodore\n" +
            "Camila\n" +
            "Luna\n" +
            "Anthony\n" +
            "Lincoln\n" +
            "Leo\n" +
            "Sofia\n" +
            "Mila\n" +
            "Jaxon\n" +
            "Aria\n" +
            "Asher\n" +
            "Scarlett\n" +
            "Riley\n" +
            "Christopher\n" +
            "Ryan\n" +
            "Ezra\n" +
            "Josiah\n" +
            "Andrew\n" +
            "Penelope\n" +
            "Thomas\n" +
            "Joshua\n" +
            "Hudson\n" +
            "Layla\n" +
            "Chloe\n" +
            "Caleb\n" +
            "Victoria\n" +
            "Madison\n" +
            "Eleanor\n" +
            "Grace\n" +
            "Nathan\n" +
            "Nora\n" +
            "Parker\n" +
            "Adrian\n" +
            "Maverick\n" +
            "Cameron\n" +
            "Elias\n" +
            "Hunter\n" +
            "Zoey\n" +
            "Hannah\n" +
            "Aaron\n" +
            "Landon\n" +
            "Lily\n" +
            "Ellie\n" +
            "Violet\n" +
            "Connor\n" +
            "Lillian\n" +
            "Jeremiah\n" +
            "Stella\n" +
            "Aurora\n" +
            "Easton\n" +
            "Roman\n" +
            "Ezekiel\n" +
            "Miles\n" +
            "Sawyer\n" +
            "Natalie\n" +
            "Everly\n" +
            "Emilia\n" +
            "Leah\n" +
            "Jameson\n" +
            "Cooper\n" +
            "Willow\n" +
            "Addison\n" +
            "Rowan\n" +
            "Nova\n" +
            "Austin\n" +
            "Luca\n" +
            "Axel\n" +
            "Lucy\n" +
            "Audrey\n" +
            "Bella\n" +
            "Skylar\n" +
            "Adam\n" +
            "Xavier\n" +
            "Savannah\n" +
            "Everett\n" +
            "Jace\n" +
            "Kai\n" +
            "Isla\n" +
            "Evan\n" +
            "Kayden\n" +
            "Declan\n" +
            "Quinn\n" +
            "Naomi\n" +
            "Elena\n" +
            "Caroline\n" +
            "Eliana\n" +
            "Anna\n" +
            "Wesley\n" +
            "Maya\n" +
            "River\n" +
            "Micah\n" +
            "Ivy\n" +
            "Brayden\n" +
            "Ariana\n" +
            "Aaliyah\n" +
            "Bennett\n" +
            "Bryson\n" +
            "Cora\n" +
            "Silas\n" +
            "Alice\n" +
            "Gabriella\n" +
            "Ryder\n" +
            "Gianna\n" +
            "Serenity\n" +
            "Samantha\n" +
            "Vincent\n" +
            "Emery\n" +
            "Sarah\n" +
            "Autumn\n" +
            "Chase\n" +
            "Hayden\n" +
            "Emerson\n" +
            "Ashton\n" +
            "Tyler\n" +
            "Sadie\n" +
            "Delilah\n" +
            "Josephine\n" +
            "Nevaeh\n" +
            "Zachary\n" +
            "Adeline\n" +
            "Braxton\n" +
            "Gavin\n" +
            "Lydia\n" +
            "Amir\n" +
            "Clara\n" +
            "Rylee\n" +
            "Madeline\n" +
            "Ryker\n" +
            "Jasper\n" +
            "Julia\n" +
            "Jade\n" +
            "Brielle\n" +
            "Finley\n" +
            "Elliot\n" +
            "Zion\n" +
            "Athena\n" +
            "Leilani\n" +
            "Jonah\n" +
            "August\n" +
            "Kaiden\n" +
            "Jayce\n" +
            "Jude\n" +
            "Lorenzo\n" +
            "Calvin\n" +
            "Liliana\n" +
            "Maddox\n" +
            "Raelynn\n" +
            "Camden\n" +
            "Rose\n" +
            "Arianna\n" +
            "Remington\n" +
            "Milo\n" +
            "Abel\n" +
            "Lyla\n" +
            "Malachi\n" +
            "Phoenix\n" +
            "Rhett\n" +
            "Aubree\n" +
            "Xander\n" +
            "Finn\n" +
            "Dakota\n" +
            "Iris\n" +
            "Ximena\n" +
            "Arthur\n" +
            "Adriel\n" +
            "Alan\n" +
            "Reese\n" +
            "Alexandra\n" +
            "Jasmine\n" +
            "Remi\n" +
            "Joel\n" +
            "Amaya\n" +
            "Ryleigh\n" +
            "Alexa\n" +
            "Amara\n" +
            "Morgan\n" +
            "Emersyn\n" +
            "Bailey\n" +
            "Brianna\n" +
            "Archer\n" +
            "Valerie\n" +
            "Anastasia\n" +
            "Eloise\n" +
            "Leon\n" +
            "Josie\n" +
            "Sage\n" +
            "Alina\n" +
            "Lucia\n" +
            "Adalyn\n" +
            "Molly\n" +
            "Ayla\n" +
            "Atlas\n" +
            "Kyler\n" +
            "Enzo\n" +
            "Esther\n" +
            "Genevieve\n" +
            "Marcus\n" +
            "Annabelle\n" +
            "Ace\n" +
            "Alyssa\n" +
            "Aliyah\n" +
            "Callie\n" +
            "Sienna\n" +
            "Jax\n" +
            "Presley\n" +
            "Javier\n" +
            "Alaia\n" +
            "Rory\n" +
            "Zane\n" +
            "Alaina\n" +
            "Knox\n" +
            "Adonis\n" +
            "Arabella\n" +
            "Paxton\n" +
            "Gemma\n" +
            "Lauren\n" +
            "Amy\n" +
            "Holden\n" +
            "Elise\n" +
            "Ada\n" +
            "Nash\n" +
            "Ariella\n" +
            "Lennox\n" +
            "Noelle\n" +
            "Mya\n" +
            "Arlo\n" +
            "Rafael\n" +
            "Cayden\n" +
            "Lila\n" +
            "Ronan\n" +
            "Ari\n" +
            "Hope\n" +
            "Kali\n" +
            "Alana\n" +
            "Rylan\n" +
            "Zara\n" +
            "Millie\n" +
            "Maeve\n" +
            "Adelyn\n" +
            "Lola\n" +
            "Elsie\n" +
            "Zander\n" +
            "Jayla\n" +
            "Vera\n" +
            "Alivia\n" +
            "Skyler\n" +
            "Nyla\n" +
            "Tessa\n" +
            "Jensen\n" +
            "Malia\n" +
            "Cali\n" +
            "Lena\n" +
            "Armani\n" +
            "Evangeline\n" +
            "Zuri\n" +
            "Jane\n" +
            "Amira\n" +
            "Adaline\n" +
            "Lia\n" +
            "Phoebe\n" +
            "Thea\n" +
            "Cruz\n" +
            "Leighton\n" +
            "Jaylen\n" +
            "Killian\n" +
            "Orion\n" +
            "Myla\n" +
            "Atticus\n" +
            "Alani\n" +
            "Kiara\n" +
            "Margot\n" +
            "Adelaide\n" +
            "Milan\n" +
            "Harlow\n" +
            "Cairo\n" +
            "Evelynn\n" +
            "Kaia\n" +
            "Nina\n" +
            "Samara\n" +
            "Giselle\n" +
            "Evie\n" +
            "Talia\n" +
            "Jessica\n" +
            "Leia\n" +
            "Lexi\n" +
            "Makenzie\n" +
            "Caiden\n" +
            "Tyson\n" +
            "Kailani\n" +
            "Willa\n" +
            "Elian\n" +
            "Malik\n" +
            "Winston\n" +
            "Raiden\n" +
            "Wren\n" +
            "Octavia\n" +
            "Celeste\n" +
            "Collin\n" +
            "Seth\n" +
            "Lainey\n" +
            "Lana\n" +
            "Ophelia\n" +
            "Lilith\n" +
            "Zayne\n" +
            "Gia\n" +
            "Sarai\n" +
            "Rhys\n" +
            "Mabel\n" +
            "Jenna\n" +
            "Kalani\n" +
            "Azariah\n" +
            "Jolene\n" +
            "Bianca\n" +
            "Lorelei\n" +
            "Annalise\n" +
            "Avianna\n" +
            "Liana\n" +
            "Ronin\n" +
            "Elianna\n" +
            "Kora\n" +
            "Cadence\n" +
            "Amber\n" +
            "Dior\n" +
            "Poppy\n" +
            "Asa\n" +
            "Sierra\n" +
            "Nia\n" +
            "Omari\n" +
            "Jazlyn\n" +
            "Mikayla\n" +
            "Kian\n" +
            "Leona\n" +
            "Reece\n" +
            "Maren\n" +
            "Kieran\n" +
            "Ryland\n" +
            "Azalea\n" +
            "Emmitt\n" +
            "Jaliyah\n" +
            "Aviana\n" +
            "Sloan\n" +
            "Janelle\n" +
            "Elaine\n" +
            "Jayleen\n" +
            "Rosie\n" +
            "Jemma\n" +
            "Kylan\n" +
            "Soren\n" +
            "Huxley\n" +
            "Jayda\n" +
            "Ares\n" +
            "Skyla").split("\n");
    public static String[] lastNames = ("Smith\n" +
            "Johnson\n" +
            "Williams\n" +
            "Jones\n" +
            "Brown\n" +
            "Davis\n" +
            "Miller\n" +
            "Wilson\n" +
            "Moore\n" +
            "Taylor\n" +
            "Anderson\n" +
            "Thomas\n" +
            "Jackson\n" +
            "White\n" +
            "Harris\n" +
            "Martin\n" +
            "Thompson\n" +
            "Garcia\n" +
            "Martinez\n" +
            "Robinson\n" +
            "Clark\n" +
            "Rodriguez\n" +
            "Lewis\n" +
            "Lee\n" +
            "Walker\n" +
            "Hall\n" +
            "Allen\n" +
            "Young\n" +
            "Hernandez\n" +
            "King\n" +
            "Wright\n" +
            "Lopez\n" +
            "Hill\n" +
            "Scott\n" +
            "Green\n" +
            "Adams\n" +
            "Baker\n" +
            "Gonzalez\n" +
            "Nelson\n" +
            "Carter\n" +
            "Mitchell\n" +
            "Perez\n" +
            "Roberts\n" +
            "Turner\n" +
            "Phillips\n" +
            "Campbell\n" +
            "Parker\n" +
            "Evans\n" +
            "Edwards\n" +
            "Collins\n" +
            "Stewart\n" +
            "Sanchez\n" +
            "Morris\n" +
            "Rogers\n" +
            "Reed\n" +
            "Cook\n" +
            "Morgan\n" +
            "Bell\n" +
            "Murphy\n" +
            "Bailey\n" +
            "Rivera\n" +
            "Cooper\n" +
            "Richardson\n" +
            "Cox\n" +
            "Howard\n" +
            "Ward\n" +
            "Torres\n" +
            "Peterson\n" +
            "Gray\n" +
            "Ramirez\n" +
            "James\n" +
            "Watson\n" +
            "Brooks\n" +
            "Kelly\n" +
            "Sanders\n" +
            "Price\n" +
            "Bennett\n" +
            "Wood\n" +
            "Barnes\n" +
            "Ross\n" +
            "Henderson\n" +
            "Coleman\n" +
            "Jenkins\n" +
            "Perry\n" +
            "Powell\n" +
            "Long\n" +
            "Patterson\n" +
            "Hughes\n" +
            "Flores\n" +
            "Washington\n" +
            "Butler\n" +
            "Simmons\n" +
            "Foster\n" +
            "Gonzales\n" +
            "Bryant\n" +
            "Alexander\n" +
            "Russell\n" +
            "Griffin\n" +
            "Diaz\n" +
            "Hayes\n" +
            "Myers\n" +
            "Ford\n" +
            "Hamilton\n" +
            "Graham\n" +
            "Sullivan\n" +
            "Wallace\n" +
            "Woods\n" +
            "Cole\n" +
            "West\n" +
            "Jordan\n" +
            "Owens\n" +
            "Reynolds\n" +
            "Fisher\n" +
            "Ellis\n" +
            "Harrison\n" +
            "Gibson\n" +
            "Mcdonald\n" +
            "Cruz\n" +
            "Marshall\n" +
            "Ortiz\n" +
            "Gomez\n" +
            "Murray\n" +
            "Freeman\n" +
            "Wells\n" +
            "Webb\n" +
            "Simpson\n" +
            "Stevens\n" +
            "Tucker\n" +
            "Porter\n" +
            "Hunter\n" +
            "Hicks\n" +
            "Crawford\n" +
            "Henry\n" +
            "Boyd\n" +
            "Mason\n" +
            "Morales\n" +
            "Kennedy\n" +
            "Warren\n" +
            "Dixon\n" +
            "Ramos\n" +
            "Reyes\n" +
            "Burns\n" +
            "Gordon\n" +
            "Shaw\n" +
            "Holmes\n" +
            "Rice\n" +
            "Robertson\n" +
            "Hunt\n" +
            "Black\n" +
            "Daniels\n" +
            "Palmer\n" +
            "Mills\n" +
            "Nichols\n" +
            "Grant\n" +
            "Knight\n" +
            "Ferguson\n" +
            "Rose\n" +
            "Stone\n" +
            "Hawkins\n" +
            "Dunn\n" +
            "Perkins\n" +
            "Hudson\n" +
            "Spencer\n" +
            "Gardner\n" +
            "Stephens\n" +
            "Payne\n" +
            "Pierce\n" +
            "Berry\n" +
            "Matthews\n" +
            "Arnold\n" +
            "Wagner\n" +
            "Willis\n" +
            "Ray\n" +
            "Watkins\n" +
            "Olson\n" +
            "Carroll\n" +
            "Duncan\n" +
            "Snyder\n" +
            "Hart\n" +
            "Cunningham\n" +
            "Bradley\n" +
            "Lane\n" +
            "Andrews\n" +
            "Ruiz\n" +
            "Harper\n" +
            "Fox\n" +
            "Riley\n" +
            "Armstrong\n" +
            "Carpenter\n" +
            "Weaver\n" +
            "Greene\n" +
            "Lawrence\n" +
            "Elliott\n" +
            "Chavez\n" +
            "Sims\n" +
            "Austin\n" +
            "Peters\n" +
            "Kelley\n" +
            "Franklin\n" +
            "Lawson\n" +
            "Fields\n" +
            "Gutierrez\n" +
            "Ryan\n" +
            "Schmidt\n" +
            "Carr\n" +
            "Vasquez\n" +
            "Castillo\n" +
            "Wheeler\n" +
            "Chapman\n" +
            "Oliver\n" +
            "Montgomery\n" +
            "Richards\n" +
            "Williamson\n" +
            "Johnston\n" +
            "Banks\n" +
            "Meyer\n" +
            "Bishop\n" +
            "Mccoy\n" +
            "Howell\n" +
            "Alvarez\n" +
            "Morrison\n" +
            "Hansen\n" +
            "Fernandez\n" +
            "Garza\n" +
            "Harvey\n" +
            "Little\n" +
            "Burton\n" +
            "Stanley\n" +
            "Nguyen\n" +
            "George\n" +
            "Jacobs\n" +
            "Reid\n" +
            "Kim\n" +
            "Fuller\n" +
            "Lynch\n" +
            "Dean\n" +
            "Gilbert\n" +
            "Garrett\n" +
            "Romero\n" +
            "Welch\n" +
            "Larson\n" +
            "Frazier\n" +
            "Burke\n" +
            "Hanson\n" +
            "Day\n" +
            "Mendoza\n" +
            "Moreno\n" +
            "Bowman\n" +
            "Medina\n" +
            "Fowler\n" +
            "Brewer\n" +
            "Hoffman\n" +
            "Carlson\n" +
            "Silva\n" +
            "Pearson\n" +
            "Holland\n" +
            "Douglas\n" +
            "Fleming\n" +
            "Jensen\n" +
            "Vargas\n" +
            "Byrd\n" +
            "Davidson\n" +
            "Hopkins\n" +
            "May\n" +
            "Terry\n" +
            "Herrera\n" +
            "Wade\n" +
            "Soto\n" +
            "Walters\n" +
            "Curtis\n" +
            "Neal\n" +
            "Caldwell\n" +
            "Lowe\n" +
            "Jennings\n" +
            "Barnett\n" +
            "Graves\n" +
            "Jimenez\n" +
            "Horton\n" +
            "Shelton\n" +
            "Barrett\n" +
            "Obrien\n" +
            "Castro\n" +
            "Sutton\n" +
            "Gregory\n" +
            "Mckinney\n" +
            "Lucas\n" +
            "Miles\n" +
            "Craig\n" +
            "Rodriquez\n" +
            "Chambers\n" +
            "Holt\n" +
            "Lambert\n" +
            "Fletcher\n" +
            "Watts\n" +
            "Bates\n" +
            "Hale\n" +
            "Rhodes\n" +
            "Pena\n" +
            "Beck\n" +
            "Newman\n" +
            "Haynes\n" +
            "Mcdaniel\n" +
            "Mendez\n" +
            "Bush\n" +
            "Vaughn\n" +
            "Parks\n" +
            "Dawson\n" +
            "Santiago\n" +
            "Norris\n" +
            "Hardy\n" +
            "Love\n" +
            "Steele\n" +
            "Curry\n" +
            "Powers\n" +
            "Schultz\n" +
            "Barker\n" +
            "Guzman\n" +
            "Page\n" +
            "Munoz\n" +
            "Ball\n" +
            "Keller\n" +
            "Chandler\n" +
            "Weber\n" +
            "Leonard\n" +
            "Walsh\n" +
            "Lyons\n" +
            "Ramsey\n" +
            "Wolfe\n" +
            "Schneider\n" +
            "Mullins\n" +
            "Benson\n" +
            "Sharp\n" +
            "Bowen\n" +
            "Daniel\n" +
            "Barber\n" +
            "Cummings\n" +
            "Hines\n" +
            "Baldwin\n" +
            "Griffith\n" +
            "Valdez\n" +
            "Hubbard\n" +
            "Salazar\n" +
            "Reeves\n" +
            "Warner\n" +
            "Stevenson\n" +
            "Burgess\n" +
            "Santos\n" +
            "Tate\n" +
            "Cross\n" +
            "Garner\n" +
            "Mann\n" +
            "Mack\n" +
            "Moss\n" +
            "Thornton\n" +
            "Dennis\n" +
            "Mcgee\n" +
            "Farmer\n" +
            "Delgado\n" +
            "Aguilar\n" +
            "Vega\n" +
            "Glover\n" +
            "Manning\n" +
            "Cohen\n" +
            "Harmon\n" +
            "Rodgers\n" +
            "Robbins\n" +
            "Newton\n" +
            "Todd\n" +
            "Blair\n" +
            "Higgins\n" +
            "Ingram\n" +
            "Reese\n" +
            "Cannon\n" +
            "Strickland\n" +
            "Townsend\n" +
            "Potter\n" +
            "Goodwin\n" +
            "Walton\n" +
            "Rowe\n" +
            "Hampton\n" +
            "Ortega\n" +
            "Patton\n" +
            "Swanson\n" +
            "Joseph\n" +
            "Francis\n" +
            "Goodman\n" +
            "Maldonado\n" +
            "Yates\n" +
            "Becker\n" +
            "Erickson\n" +
            "Hodges\n" +
            "Rios\n" +
            "Conner\n" +
            "Adkins\n" +
            "Webster\n" +
            "Norman\n" +
            "Malone\n" +
            "Hammond\n" +
            "Flowers\n" +
            "Cobb").split("\n");
    public static String[] fields = {
            "Computer Science",
            "Architecture",
            "Biotechnology",
            "Electrical Engineering",
            "Industrial Management",
            "Information and Communication Technology",
            "Chemical Engineering",
            "Mechanical Engineering",
            "Mathematics",
            "Material Science and Engineering",
            "Environmental Engineering",
            "Medical Engineering",
            "Engineering Physics",
            "Human Resources",
            "Social Services",
            "Journalism",
            "Film & TV",
            "Music",
            "Childcare",
            "Culinary Arts"
    };

}
